name: Publish Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: |
        cd PrimeService
        dotnet restore
    
    - name: Build
      run: |
        cd PrimeService
        dotnet build --no-restore
    
    - name: Test with coverage
      run: |
        cd PrimeService
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../CoverageResults/
    
    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: './PrimeService/CoverageResults/coverage.cobertura.xml'
        targetdir: './CoverageReport'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
    
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: CoverageReport
        path: CoverageReport
    
    - name: Deploy coverage report to GitHub Pages
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./CoverageReport
        destination_dir: coverage
        force_orphan: false
