name: Publish Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install DocFX
      run: |
        dotnet tool install -g docfx
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    
    - name: Generate XML Documentation
      run: |
        cd PrimeService
        dotnet build -c Release /p:GenerateDocumentationFile=true
    
    - name: Build Documentation
      run: |
        cd docs
        docfx docfx.json
    
    - name: Deploy to GitHub Pages
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./docs/_site
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean-exclude: |
          coverage/**
        single-commit: true
        commit-message: 'docs: update API documentation'
