name: Publish Coverage Report

on:
  workflow_run:
    workflows: ["Publish Documentation"]
    types:
      - completed
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install coverlet
      run: dotnet tool install --global coverlet.console
    
    - name: Restore dependencies
      run: |
        cd PrimeService
        dotnet restore
    
    - name: Build
      run: |
        cd PrimeService
        dotnet build --configuration Release
    
    - name: Test with coverage
      run: |
        cd PrimeService
        dotnet test --configuration Release --no-build --verbosity normal \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=cobertura
        
        # Encontrar y copiar el archivo de cobertura
        find . -name "coverage.cobertura.xml" -type f -exec cp {} ../coverage.cobertura.xml \;
        mkdir -p ../CoverageReport
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:../coverage.cobertura.xml -targetdir:../CoverageReport -reporttypes:"HtmlInline_AzurePipelines;Cobertura;Badges"
    
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: CoverageReport
    
    - name: Deploy coverage report to GitHub Pages
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./CoverageReport
        target-folder: coverage
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: false
        clean-exclude: |
          **/*
        single-commit: false
        commit-message: 'docs: update coverage report'
