name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: |
        cd PrimeService
        dotnet restore
    
    - name: Build
      run: |
        cd PrimeService
        dotnet build --configuration Release --no-restore
    
    - name: Test
      run: |
        cd PrimeService
        dotnet test --configuration Release --no-build --verbosity normal
    
    - name: Pack NuGet package
      run: |
        cd PrimeService/Primes.Lib
        dotnet pack --configuration Release -p:PackageVersion=2022074258 /p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }}
    
    - name: Push to GitHub Packages
      run: |
        cd PrimeService/Primes.Lib
        dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v2022074258-${{ github.run_number }}
        release_name: Release v2022074258-${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Upload NuGet package to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v2022074258-${{ github.run_number }}
        files: ./PrimeService/Primes.Lib/bin/Release/Primes.Lib.2022074258.nupkg
        token: ${{ secrets.GITHUB_TOKEN }}
